### ISSUE TITLE
JAWS 2021 Keyboard navigation broken in 1.2.0 release.

### ISSUE THREAD

**Issue by thomaskendrick** [duetds/date-picker#72] opened 2021-03-03 16:30 UTC
**Describe the bug**
Keyboard navigation not functioning correctly using JAWS 2021 (2021.2102.34 ILM). When translating across the days using the arrow keys. Keypresses appear to scroll through individual characters rather than days. It appears that this behaviour was introduced 1.2.0 release as 1.1.0 functions fine.

**To Reproduce**
1. Navigate to https://duetds.github.io/date-picker/ whilst using JAWS 2021
2. Open the Duet date picker in one of the examples.
3. Attempt to navigate across the days using directional arrows.

**Expected behavior**
A single keypress should move the cursor across one day, instead it appears to navigate through the individual characters of the day.

**Screenshots**

https://user-images.githubusercontent.com/49865372/109837400-0db8db80-7c3d-11eb-9379-f73495e31e12.mp4

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Home 10.0.19042 Build 19042
 - Browser: Replicated in both Chrome Version 88.0.4324.190 (Official Build) (64-bit) and Firefox 86.0

**Additional context**
We've resolved this issue on our end by pinning the version to 1.1.0, however we're keen to keep our deps current. 

Thanks!

**Comment by WickyNilliams** [comment] 2021-03-03 17:00
I believe this is the expected behaviour in JAWS, and the previous version would be considered surprising behaviour.

In its default mode, JAWS intercepts arrow keys and reads individual characters with left/right arrows. 

When entering the calendar, it is announced as a table, and so you can/should use JAWS [table navigation commands](https://dequeuniversity.com/screenreaders/jaws-keyboard-shortcuts#jaws-tables) to move around the table. The benefit of this is that it announces column headers (days in this case), and will also announce the row/column numbers, both of which provide important context to visually impaired users. 

In 1.1.0, the column headers were never announced, which harms the UX considerably. 

Users can switch to application/form mode which will allow pass through of arrow keys, and then the arrow keys will work as you expected. IIRC the shortcut for this is <kbd>Insert</kbd> + <kbd>Space</kbd>.

This behaviour is roughly the same in NVDA also.

Some relevant issues discussing this behaviour:

* https://github.com/duetds/date-picker/issues/13
* https://github.com/duetds/date-picker/issues/26

I am far from an experienced user when it comes to screenreaders, so forgive me if I'm wrong here! Happy to discuss further regardless.

There are options that allow you to register keyboard shortcuts with screenreaders, or even force into application/forms mode, but I am not sure it is worth doing that since an experienced user can switch modes themselves.

**Comment by WickyNilliams** [comment] 2021-04-30 10:04
Closing as I think this is intended behaviour and not an issue. Please let me know if you disagree!

**Closed by WickyNilliams** 2021-04-30 10:04 UTC
