### ISSUE TITLE
Highlight the specific dates

### ISSUE THREAD

**Issue by mattdamon108** [duetds/date-picker#67] opened 2021-02-08 08:58 UTC
**Is your feature request related to a problem? Please describe.**
In case of using it in diary application for example, I'd like to highlight the specific dates I wrote the diary. But I couldn't find the feature about it.

**Describe the solution you'd like**
a `selected` property can be populated with an array of dates to highlight.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by WickyNilliams** [comment] 2021-06-18 11:32
Closing as duplicate of #61

**Closed by WickyNilliams** 2021-06-18 11:32 UTC
